services:
  - name: laravel-app
    type: web
    env: docker
    repo: https://github.com/Javed-Shekh777/hospital_appointment
    branch: main
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: bilaalw2ovu1zcpaxz2q-mysql.services.clever-cloud.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: bilaalw2ovu1zcpaxz2q
      - key: DB_USERNAME
        value: uyhrxb70otikl5rv
      - key: DB_PASSWORD
        value: mlJXkEvxFoKvjfIindQJ
    buildCommand: |
      chmod +x render-build.sh
      ./render-build.sh    
